version: "3.9"

services:
  elasticsearch:
    image: elasticsearch:${STACK_VERSION}
    container_name: elasticsearch
    volumes:
      - type: volume
        source: es_data
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
      - xpack.security.enabled=false
    networks:
      - elastic

  kibana:
    image: kibana:${STACK_VERSION}
    container_name: kibana
    ports:
      - target: 5601
        published: 5601
    depends_on:
      - elasticsearch
    networks:
      - elastic  

  logstash:
    image: logstash:${STACK_VERSION}
    container_name: logstash
    depends_on:
      - elasticsearch
    volumes:
      - ./product/pipeline/:/usr/share/logstash/pipeline/
      - ./product/config/pipeline.yml:/usr/share/logstash/config/pipeline.yml
      - ./mysqlConnector/mysql-connector-java-8.0.22.jar:/home/mysql-connector-java-8.0.22.jar
    environment:
      - ELASTIC_HOST=elasticsearch
      - MYSQL_HOST=mysql
    networks:
      - elastic

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: product
      MYSQL_TCP_PORT: 3306
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - ./database/product.sql:/docker-entrypoint-initdb.d/product.sql:ro
    ports:
      - "3306:3306"
    networks:
      - elastic

volumes:
  es_data:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge
